images/urls.py
from django.urls import path

from . import views

app_name = 'images'

urlpatterns = [
    path('', views.image_list, name='list'),
    path('create/', views.image_create, name='create'),
    path('<int:img_id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
]

images/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.urls import reverse

from a_social_project.utils import get_random_str

from .utils import image_upload_path

User = get_user_model()


class Image(models.Model):
    user = models.ForeignKey(User, related_name='images_created', on_delete=models.CASCADE, blank=True)
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to=image_upload_path)
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(User, related_name='images_liked', blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = f"{slugify(self.title)} {get_random_str(size=5)}"
            self.slug = slugify(self.slug)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from django.utils.text import slugify
from django.core.files.base import ContentFile

from urllib import request

from a_social_project.utils import get_random_str

from .models import Image


class ImageCreationForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError("have to enter JPEG URLS only")
        return url

    def save(self, force_insert=False, force_update=False, commit=True, *args, **kwargs):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(self.cleaned_data['title'])
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f"{name}-{get_random_str(size=5)}.{extension}"
        response = request.urlopen(image_url)
        user = kwargs.get('user' or None)
        if user is not None:
            image.user = user
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count

from common.decorators import ajax_required
from actions.utils import create_action

from .forms import ImageCreationForm
from .models import Image


@login_required
def image_create(request):
    if request.method == "POST":
        form = ImageCreationForm(data=request.POST)
        print("Is coming to POST")
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False, user=request.user)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'Bookmarked Image', new_item)
            messages.success(request, "Image created")
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreationForm(data=request.GET)
    context = {
        'section': 'images',
        'form': form
    }
    return render(request, 'images/image/create.html', context)


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse()
        images = paginator.page(paginator.num_pages)
    context = {
        'section': 'images',
        'images': images,
    }
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html', context)
    return render(request, 'images/image/list.html', context)


def image_detail(request, img_id=None, slug=None):
    image = get_object_or_404(Image, id=img_id, slug=slug)
    context = {
        'section': 'images',
        'image': image
    }
    return render(request, 'images/image/detail.html', context)


@login_required
@require_POST
@ajax_required
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action').strip()
    print(image_id, action)
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes image', image)
            else:
                image.users_like.remove(request.user)
        except:
            pass
        return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'error'})

images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview" alt="">
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock %}
{% block content %}
    {% include 'includes/messages.html' %}
    <h1>{{ image.title }}</h1>
    <a href="{{ image.image.url }}">
        <img src="{% thumbnail image.image 300x0 %}" class="image-detail" alt="">
    </a>
    {% with total_likes=image.users_like.count user_likes=image.users_like.all %}
        <div class="image-info">
            <div>
                <span class="count">
                    <span class="total">{{ total_likes }}</span>
                     like{{ total_likes|pluralize }}
                </span>
                <a href="#" data-id="{{ image.id }}" data-action="
                                {% if request.user in user_likes %}un{% endif %}like"
                   class="like button">
                    {% if request.user not in user_likes %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
            </div>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            {% for user in user_likes %}
                <div>
                    {% if user.profile.photo %}
                        <img src="{{ user.profile.photo.url }}" alt="">
                    {% endif %}
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            $('a.like').click(function (e) {
                e.preventDefault();
                $.post('{% url "images:like" %}',
                    {
                        id: $(this).data('id'),
                        action: $(this).data('action')
                    },
                    function (data) {
                        if (data['status'] === 'ok') {
                            var aLike = $('a.like');
                            var previous_action = aLike.data('action');
                            aLike.data('action', previous_action === 'like' ? 'unlike' : 'like');
                            aLike.text(previous_action === 'like' ? 'Unlike' : 'Like');
                            var spTotalCount = $('span.count .total')
                            var previous_likes = parseInt(spTotalCount.text());
                            spTotalCount.text(
                                previous_action === 'like' ? previous_likes + 1 : previous_likes - 1);
                        }
                    }
                )
            })
        })
    </script>
{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {
            var page = 1;
            var empty_page = false;
            var block_request = false;
            $(window).scroll(function () {
                var margin = $(document).height() - $(window).height() - 200;
                if ($(window).scrollTop() > margin && empty_page === false && block_request === false) {
                    block_request = true;
                    page += 1;
                    $.get('?page=' + page, function (data) {
                        if (data === '') {
                            empty_page = true;
                        } else {
                            block_request = false;
                            $('#image-list').append(data);
                        }
                    });
                }
            });
        })
    </script>

{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop="smart" as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}" alt="">
            </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}